# Generated by Django 5.0.14 on 2026-07-23 00:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParteTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de fin')),
                ('acciones', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Acciones por equipo')),
                ('cantidad_equipos', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad de equipos')),
                ('total_acciones', models.PositiveIntegerField(default=0, verbose_name='Total de acciones')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partes_creados', to='inventario.persona', verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Parte de trabajo',
                'verbose_name_plural': 'Partes de trabajo',
                'ordering': ['-fecha_inicio', '-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='PartePersona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas_trabajadas', models.DecimalField(decimal_places=2, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Horas trabajadas')),
                ('horas_extras', models.DecimalField(decimal_places=2, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Horas extra')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partes', to='inventario.persona', verbose_name='Persona')),
                ('parte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personas', to='inventario.partetrabajo', verbose_name='Parte de trabajo')),
            ],
            options={
                'verbose_name': 'Persona en parte',
                'verbose_name_plural': 'Personas en partes',
                'unique_together': {('parte', 'persona')},
            },
        ),
    ]
