# Generated by Django 5.0.14 on 2026-07-23 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_seed_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipio', models.CharField(max_length=200, verbose_name='Municipio')),
                ('unidad_salud', models.CharField(max_length=300, verbose_name='Unidad de salud')),
                ('tipo', models.CharField(choices=[('RX', 'Rayos X'), ('USD', 'Ultrasonido'), ('OTRO', 'Otro')], default='OTRO', max_length=50, verbose_name='Tipo')),
                ('denominacion', models.CharField(blank=True, max_length=300, verbose_name='Denominación')),
                ('servicio', models.CharField(blank=True, max_length=200, verbose_name='Servicio')),
                ('local', models.CharField(blank=True, max_length=200, verbose_name='Local')),
                ('marca', models.CharField(blank=True, max_length=200, verbose_name='Marca')),
                ('modelo', models.CharField(blank=True, max_length=200, verbose_name='Modelo')),
                ('numero_serie', models.CharField(blank=True, max_length=200, verbose_name='N° de Serie')),
                ('estado', models.CharField(blank=True, choices=[('Funcionando', 'Funcionando'), ('Afectado', 'Afectado'), ('Roto', 'Roto')], max_length=50, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('frecuencia', models.CharField(blank=True, max_length=100, verbose_name='Frecuencia de mantenimiento')),
                ('fuente', models.CharField(blank=True, max_length=100, verbose_name='Archivo fuente')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'ordering': ['municipio', 'unidad_salud', 'denominacion'],
            },
        ),
    ]
