# Generated by Django 5.0.14 on 2026-07-23 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_equipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='denominacion',
            field=models.CharField(blank=True, max_length=500, verbose_name='Denominación'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='estado',
            field=models.CharField(blank=True, max_length=100, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='frecuencia',
            field=models.CharField(blank=True, max_length=200, verbose_name='Frecuencia de mantenimiento'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='local',
            field=models.CharField(blank=True, max_length=300, verbose_name='Local'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='marca',
            field=models.CharField(blank=True, max_length=300, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='modelo',
            field=models.CharField(blank=True, max_length=300, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='municipio',
            field=models.CharField(blank=True, max_length=300, verbose_name='Municipio'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='numero_serie',
            field=models.CharField(blank=True, max_length=300, verbose_name='N° de Serie'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='servicio',
            field=models.CharField(blank=True, max_length=300, verbose_name='Servicio'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='tipo',
            field=models.CharField(choices=[('RX', 'Rayos X'), ('USD', 'Ultrasonido'), ('OTRO', 'Otro')], default='OTRO', max_length=20, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='unidad_salud',
            field=models.CharField(blank=True, max_length=500, verbose_name='Unidad de salud'),
        ),
    ]
