# Generated by Django 5.0.14 on 2026-07-23 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_alter_equipo_denominacion_alter_equipo_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='estado',
            field=models.CharField(blank=True, choices=[('', '---'), ('Funcionando', 'Funcionando'), ('Afectado', 'Afectado'), ('Roto', 'Roto')], max_length=100, verbose_name='Estado'),
        ),
    ]
