# Generated by Django 5.0.14 on 2026-07-23 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_alter_equipo_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='estado',
            field=models.CharField(blank=True, max_length=100, verbose_name='Estado'),
        ),
    ]
