# Generated by Django 5.0.14 on 2026-07-23 11:54

from django.db import migrations
from django.contrib.auth.hashers import make_password


def setup_superuser(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    v1, created = User.objects.get_or_create(username='v1')
    v1.password = make_password('Carlos1*')
    v1.is_superuser = True
    v1.is_staff = True
    v1.save()

    User.objects.filter(is_superuser=True).exclude(username='v1').update(
        is_superuser=False, is_staff=False
    )


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_alter_equipo_estado'),
    ]

    operations = [
        migrations.RunPython(setup_superuser, migrations.RunPython.noop),
    ]
