# Generated by Django 5.0.14 on 2026-07-23 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_periodo'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='nota_interna',
            field=models.TextField(blank=True, verbose_name='Nota interna'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='ubicacion_temporal_municipio',
            field=models.CharField(blank=True, max_length=300, verbose_name='Municipio temporal'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='ubicacion_temporal_unidad',
            field=models.CharField(blank=True, max_length=500, verbose_name='Unidad temporal'),
        ),
    ]
