# Generated by Django 5.0.14 on 2026-08-09 21:41
# MODIFICADO (fix fresh installs): los 4 campos FK se añaden como null=True
# SIN default callable (departamento_por_defecto consultaba el ORM actual en un
# punto del esquema donde la columna centro no existía). 0014 asigna valores y
# 0019_*_not_null los vuelve NOT NULL. Las BDs ya migradas no se ven afectadas.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0012_visitalink'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True, verbose_name='Nombre')),
                ('contrasena', models.CharField(max_length=255, verbose_name='Contraseña')),
                ('restringido', models.BooleanField(default=True, verbose_name='Restringido')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='equipo',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipos', to='inventario.departamento', verbose_name='Departamento'),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_trabajo', to='inventario.departamento', verbose_name='Departamento'),
        ),
        migrations.AddField(
            model_name='partetrabajo',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='partes', to='inventario.departamento', verbose_name='Departamento'),
        ),
        migrations.AddField(
            model_name='persona',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='personas', to='inventario.departamento', verbose_name='Departamento'),
        ),
    ]
