# Generated by Django 5.0.14 on 2026-08-10 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0014_asignar_departamento_imagenologia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contrasena_centro', models.CharField(max_length=255, verbose_name='Contraseña del centro')),
                ('exigir_login_centro', models.BooleanField(default=False, help_text='Si está activa, hay que entrar primero como centro (CICEM) antes del login de departamento.', verbose_name='Exigir login del centro')),
                ('exigir_contrasena_personas', models.BooleanField(default=False, help_text='Si está activa, las personas de los departamentos necesitan contraseña para entrar.', verbose_name='Exigir contraseña de personas')),
            ],
            options={
                'verbose_name': 'Configuración',
                'verbose_name_plural': 'Configuración',
            },
        ),
        migrations.AddField(
            model_name='persona',
            name='contrasena',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Contraseña'),
        ),
    ]
