# Generated by Django 5.0.14 on 2026-08-17 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0022_persona_centro_origen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cambiopendiente',
            name='tipo',
            field=models.CharField(choices=[('creacion', 'Creación'), ('edicion', 'Edición'), ('eliminacion', 'Eliminación')], max_length=20, verbose_name='Tipo'),
        ),
    ]
