# Generated by Django 5.0.14 on 2026-08-18 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0023_alter_cambiopendiente_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='centro',
            name='contrasena',
            field=models.CharField(blank=True, help_text='Si se define, este centro usa su propia contraseña; si queda vacía, usa la contraseña global del sistema.', max_length=255, null=True, verbose_name='Contraseña del centro'),
        ),
    ]
