from django.urls import path
from . import views

urlpatterns = [
    path('', views.dashboard, name='dashboard'),

    path('personas/', views.persona_list, name='persona_list'),
    path('personas/<int:pk>/', views.persona_detail, name='persona_detail'),
    path('personas/nueva/', views.persona_create, name='persona_create'),
    path('personas/<int:pk>/editar/', views.persona_update, name='persona_update'),
    path('personas/<int:pk>/eliminar/', views.persona_delete, name='persona_delete'),

    path('ordenes/', views.orden_list, name='orden_list'),
    path('ordenes/nueva/', views.orden_create, name='orden_create'),
    path('ordenes/<int:pk>/', views.orden_detail, name='orden_detail'),
    path('ordenes/<int:pk>/editar/', views.orden_update, name='orden_update'),
    path('ordenes/<int:pk>/eliminar/', views.orden_delete, name='orden_delete'),

    path('asignacion/<int:pk>/eliminar/', views.asignacion_delete, name='asignacion_delete'),

    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('crear-departamento/', views.crear_departamento, name='crear_departamento'),
    path('departamentos/', views.departamentos_admin, name='departamentos_admin'),
    path('departamentos/<int:pk>/toggle-restringido/', views.departamento_toggle_restringido, name='departamento_toggle_restringido'),
    path('departamentos/<int:pk>/toggle-activo/', views.departamento_toggle_activo, name='departamento_toggle_activo'),
    path('departamentos/<int:pk>/editar/', views.departamento_editar, name='departamento_editar'),
    path('departamentos/<int:pk>/contrasena/', views.departamento_contrasena, name='departamento_contrasena'),
    path('departamentos/configuracion/toggle/<str:etiqueta>/', views.configuracion_toggle_etiqueta, name='configuracion_toggle_etiqueta'),
    path('departamentos/configuracion/contrasena-centro/', views.configuracion_cambiar_contrasena_centro, name='configuracion_cambiar_contrasena_centro'),
    path('select-persona/', views.select_persona, name='select_persona'),
    path('generar-orden/', views.generar_orden, name='generar_orden'),
    path('partes/<int:pk>/editar/', views.parte_update, name='parte_update'),
    path('partes/<int:pk>/eliminar/', views.parte_delete, name='parte_delete'),
    path('equipos/', views.equipo_list, name='equipo_list'),
    path('equipos/estadisticas/', views.equipo_estadisticas, name='equipo_estadisticas'),
    path('equipos/nuevo/', views.equipo_create, name='equipo_create'),
    path('equipos/<int:pk>/editar/', views.equipo_update, name='equipo_update'),
    path('equipos/<int:pk>/eliminar/', views.equipo_delete, name='equipo_delete'),
    path('equipos/<int:pk>/ubicacion/', views.equipo_ubicacion, name='equipo_ubicacion'),
    path('equipos/duplicados/', views.equipo_duplicados, name='equipo_duplicados'),
    path('periodos/', views.periodo_list, name='periodo_list'),
    path('periodos/nuevo/', views.periodo_create, name='periodo_create'),
    path('periodos/<int:pk>/eliminar/', views.periodo_delete, name='periodo_delete'),
    path('historial/', views.historial, name='historial'),
    path('historial/limpiar/', views.historial_clear, name='historial_clear'),
    path('admin-panel/', views.admin_panel, name='admin_panel'),
    path('admin-panel/generar-enlace/', views.generar_enlace, name='generar_enlace'),
    path('admin-panel/eliminar-enlace/<int:pk>/', views.eliminar_enlace, name='eliminar_enlace'),
    path('visitar/<uuid:uuid_code>/', views.visitar, name='visitar'),
    path('visitar/<uuid:uuid_code>/entrar/', views.visitar_entrar, name='visitar_entrar'),
    path('exit-visitor/', views.exit_visitor, name='exit_visitor'),

    # Jerarquía de centros territoriales (Fase 3)
    path('aprobaciones/', views.solicitud_list, name='solicitud_list'),
    path('aprobaciones/solicitudes/<int:pk>/aprobar/', views.solicitud_aprobar, name='solicitud_aprobar'),
    path('aprobaciones/solicitudes/<int:pk>/cancelar/', views.solicitud_cancelar, name='solicitud_cancelar'),
    path('aprobaciones/cambios/<int:pk>/aprobar/', views.cambio_aprobar, name='cambio_aprobar'),
    path('aprobaciones/cambios/<int:pk>/cancelar/', views.cambio_cancelar, name='cambio_cancelar'),
    path('centros/', views.centro_list, name='centro_list'),
    path('centros/nuevo/', views.centro_create, name='centro_create'),
    path('centros/<int:pk>/editar/', views.centro_edit, name='centro_edit'),
    path('centros/contraseñas/', views.centro_contrasenas, name='centro_contrasenas'),
    path('municipios/', views.municipio_list, name='municipio_list'),
    path('municipios/nuevo/', views.municipio_create, name='municipio_create'),
    path('guia/', views.guia_pdf, name='guia_pdf'),
]
